# Allows you to choose which method to use in order to parse the image.
backend = "kmeans"

# What colorspace to use to gather the most prominent colors
color_space = "labmixed"

# Uses the colors gathered from color_space in a way that makes sense, resulting in a scheme palette
palette = "dark16"


[templates]

hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/wallust/wallust-hyprland.conf'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/wallust/colors-waybar.css'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/kitty-colors.conf'

cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'

